version: '3.9'

services:
  db:
    image: postgres:15
    container_name: football-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    networks:
      - football-net
    expose:
      - 5432

  scraper:
    build: ./scraper
    container_name: football-scraper
    environment:
      DB_HOST: db
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    depends_on:
      - db
    networks:
      - football-net
    expose:
      - 8000

  qt:
    user: "${UID}:${GID}"
    build: ./qt
    container_name: football-qt
    environment:
      DB_HOST: db
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      SCRAPER_HOST: scraper
      DISPLAY: ${DISPLAY}
      XDG_RUNTIME_DIR: ${XDG_RUNTIME_DIR}
      PROJECT_NAME: ${PROJECT_NAME}
      EXECUTABLE: ${EXECUTABLE}
    volumes:
      - ./qt:/app
      - ${XDG_RUNTIME_DIR}:${XDG_RUNTIME_DIR}
      - /tmp/.X11-unix:/tmp/.X11-unix
    depends_on:
      - db
      - scraper
    networks:
      - football-net

volumes:
  db_data:

networks:
  football-net:
    driver: bridge
